project:
  type: website

website:
  title: "Gerhard Riener"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: data.qmd
        text: Data
      - href: about.qmd

execute:
  freeze: true
    
format:
  html:
    theme: lumen
    css: styles.css
    toc: true




