---
title: "About"
about:
  template: jolla
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com/Gerie1979
    - icon: github
      text: Github
      href: https://github.com/gerhardriener
    - icon: mastodon
      aria-label: Mastodon
      text: Mastodon
      href: https://econtwitter.net/web/@gerhardriener
    - icon: box-arrow-in-up-right
      text: "Southampton"
      href: https://www.dice.hhu.de/diceteam/professorinnen-und-professoren/riener
---
I am professor of economics at the University of Southampton. My research interests include experimental methods in economics, field experiments in labor, education economics and the economics of charitable giving. I also conduct laboratory experiments to investigate human biases in decision making.

[Mastodon verification](https://econtwitter.net/@gerhardriener){rel="me" style="display: none;"}


## Bio

University of Essex, UK |PhD in Economics | Sep 2005 - July 2010

Institute for Advanced Studies Vienna, Austria |
Diploma in Economics and Econometrics | Sep 2003 - Aug 2005

University of Vienna, Austria |
Magister rer.soc.oec | Sep 2000 - Sep 2003

## Experience
University of Southampton | Professor | January 2023 - present

Institute for Advanced Studies Vienna | Research Fellow | May 2022 - present

Heinrich Heine University Düsseldorf | Lab Manager | June 2022 - January 2023

Georg August University Göttingen | Temporary Lecturer |  2012 - present  

Heinrich Heine University Düsseldorf | Assistant Professor | April 2012 - May 2022

Friedrich Schiller University Jena | Postdoc | 2010-2012
