---
title: "Publications"
---
(1) *Reacting to ambiguous messages: An experimental analysis* with Christian Kellner (Southampton) and Mark LeQuement (East Anglia), *Games and Economic Behavior* **accepted**
(1) Petrishcheva, V.; Riener, G.; Schildberg-Hörisch, H. Loss Aversion in Social Image Concerns. *Experimental Economics* **accepted**
(1) Wagner, V.; Riener, G. Motivation in a Reciprocal Task: Interaction Effects of Task Meaning, Goal Salience, and Time Pressure. *The B.E. Journal of Economic Analysis & Policy* **2022**.<https://doi.org/10.1515/bejeap-2021-0254>.\
(2) Riener, G.; Wagner, V. Non-Monetary Rewards in Education.
*Educational Psychology* **2022**, *42* (2), 222--239. <https://doi.org/10.1080/01443410.2021.1971159>.\
(2) Dertwinkel-Kalt, M.; Gerhardt, H.; Riener, G.; Schwerter, F.; Strang, L. Concentration Bias in Intertemporal Choice. *The Review of Economic Studies* **2021**, rdab043. <https://doi.org/10.1093/restud/rdab043>.\
(4) Riener, G.; Wagner, V. On the Design of Non-Monetary Incentives in
Schools. *Education Economics* **2019**, *27* (3), 223--240.
<https://doi.org/10.1080/09645292.2019.1586835>.\
(3) Kellner, C.; Reinstein, D.; Riener, G. Ex-Ante Commitments to "Give If You Win" Exceed Donations after a Win. *Journal of Public Economics* **2019**, *169*, 109--127. <https://doi.org/10.1016/j.jpubeco.2018.10.009>.\
(4) Riener, G.; Wagner, V. Shying Away from Demanding Tasks? Experimental Evidence on Gender Differences in Answering Multiple-Choice Questions. *Economics of Education Review* **2017**, *59* (Supplement C), 43--62. <https://doi.org/10.1016/j.econedurev.2017.06.005>.\
(5) Regner, T.; Riener, G. Privacy Is Precious: On the Attempt to Lift Anonymity on the Internet to Increase Revenue. *Journal of Economics & Management Strategy* **2017**, *26* (2), 318--336. <https://doi.org/10.1111/jems.12192>.\
(6) Ibanez, M.; Riener, G. Sorting through Affirmative Action: Three Field Experiments in Colombia. *Journal of Labor Economics* **2017**, *36* (2), 437--478. <https://doi.org/10.1086/694469>.\
(7) Gaudeul, A.; Crosetto, P.; Riener, G. Better Stuck Together or Free to Go? Of the Stability of Cooperation When Individuals Have Outside Options. *Journal of Economic Psychology* **2017**, *59*, 99--112. <https://doi.org/10.1016/j.joep.2017.01.005>.\
(8) Riener, G.; Wiederhold, S. Team Building and Hidden Costs of Control. *Journal of Economic Behavior & Organization* **2016**, *123*, 1--18. <https://doi.org/10.1016/j.jebo.2015.12.008>.\
(9) Lambarraa, F.; Riener, G. On the Norms of Charitable Giving in Islam: Two Field Experiments in Morocco. *Journal of Economic Behavior & Organization* **2015**, *118*, 69--84. <https://doi.org/10.1016/j.jebo.2015.05.006>.\
(10) Heblich, S.; Lameli, A.; Riener, G. The Effect of Perceived Regional Accents on Individual Economic Behavior: A Lab Experiment on Linguistic Performance, Cognitive Ratings and Economic Decisions. *PloS one* **2015**, *10* (2), e0113475. <https://doi.org/10.1371/journal.pone.0113475>.\
(11) Kellner, C.; Riener, G. The Effect of Ambiguity Aversion on Reward Scheme Choice. *Economics Letters* **2014**, *125* (1), 134--137. <https://doi.org/10.1016/j.econlet.2014.08.025>.\
(12) Riener, G.; Wiederhold, S. Heterogeneous Treatment Effects in Groups. *Economics Letters* **2013**, *120* (3), 408--412. <https://doi.org/10.1016/j.econlet.2013.05.016>.\
(13) Riener, G.; Traxler, C. Norms, Moods, and Free Lunch: Longitudinal Evidence on Payments from a Pay-What-You-Want Restaurant. *Journal of Socio-Economics* **2012**. <https://doi.org/10.1016/j.socec.2011.07.003>.\
(14) Gneezy, A.; Gneezy, U.; Riener, G.; Nelson, L. D. Pay-What-You-Want, Identity, and Self-Signaling in Markets. *Proceedings of the National Academy of Sciences PNAS* **2012**. <https://doi.org/10.1073/pnas.1120893109>.\
(15) Riener, G. Inequality and Mobility of Household Incomes in Europe: Evidence from the ECHP. *Applied Economics* **2011**, *44* (3), 279--288. <https://doi.org/10.1080/00036846.2010.505555>.\
(16) Reinstein, D.; Riener, G. Reputation and Influence in Charitable Giving: An Experiment. *Theory and Decision* **2011**, *72* (2), 221--243. <https://doi.org/10.1007/s11238-011-9245-8>.\
(17) Reinstein, D.; Riener, G. Decomposing Desert and Tangibility Effects in a Charitable Giving Experiment. *Experimental Economics* **2011**, *15* (1), 229--240. <https://doi.org/10.1007/s10683-011-9298-0>.\
(18) Hugh-Jones, D.; Katsanidou, A.; Riener, G. Intergroup Conflict and the Media: An Experimental Study of Greek Students after the 2008 Riots. *International Journal of Conflict and Violence* **2011**, *5* (2), 325--344.
